[package]
name = "satisfactory_alt_recipe"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.27"
macroquad = "0.3.25"
serde = {version = "1.0.159", features = ["derive"]}
serde_json = "1.0.95"

